= Spring Web and Reactive

Spring has two primary ways of interacting with web based calls:  MVC and Reactive.  When to use which is complex, but simply Reactive apps are
designed to work at significant scale using Non-Blocking I/O and high concurrency.  If your app doesn't need huge scale, it may not be worth 
adopting Reactive.  Of course, there's nothing wrong with using Reactive patterns even if you're not running at hyperscale.

Along with exposing endpoints, there is also the case where an application wants to act as a client to a service.  Again, there are 
two ways.  Traditional RestTemplate and the new, reactive WebClient.

This module will explore each of these.

Docs: link:https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc[Spring MVC] and link:https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html[Reactive Web]

link:https://github.com/rstoyanchev/reactive-for-webmvc[Rosen Code]

== Get the project

The completed exercise from the last lab is the starting point for this one.

. Go to your project in your IDE.  If you don't have a project already available you can use the baseline project from Building a Boot Application.
+
[source,bash]
---------------------------------------------------------------------
spring-workshop-2020:
├── labs
│   ├── build_a_boot_app
│       └── greeting-service-baseline
---------------------------------------------------------------------

== Extend the MVC Controller

We'll add an "echo" endpoint that will take a Greeting and send it back prepended with "echo:".

. Open GreetingServiceController.java

. Add the echo method
+
[source, java]
.GreetingServiceController.java
---------------------------------------------------------------------
    @PostMapping("/echo")
    Greeting echo(@RequestBody Greeting inGreeting) {
        return new Greeting("echo: "+inGreeting.greeting);
    }
---------------------------------------------------------------------

. Build and run the app
. Test with a tool that can do a POST, such as Postman or use curl
+
----
curl --header "Content-Type: application/json" \
     --request POST \
     --data '{"greeting":"hello"}' \
     http://localhost:8080/echo
----

== Traditional Web Client

When your application needs to call another web endpoint we can use RestTemplate.

. Generate a RestTemplate Bean in GreetingServiceConfig
+
[source, java]
.GreetingServiceConfig.java
---------------------------------------------------------------------
    @Bean
    RestTemplate getRestTemplate() {
        RestTemplate restTemplate = new RestTemplate();
        String baseUrl = "http://localhost:8080/";  //Make this a property later
        restTemplate.setUriTemplateHandler(new DefaultUriBuilderFactory(baseUrl));
        return restTemplate;
    }
---------------------------------------------------------------------

. Inject it into the GreetingServiceController.  The local members and the constructor will now look like this:
+
[source, java]
.GreetingServiceController.java
---------------------------------------------------------------------
    final private Greeting greeting;
    final private RestTemplate restTemplate;

    public GreetingServiceController(Greeting greeting, RestTemplate restTemplate) {
        super();
        this.greeting = greeting;
        this.restTemplate = restTemplate;
    }
---------------------------------------------------------------------

. Create an endpoint to trigger the RestTemplate to call our Greeting service and return the result.  (Sure, it's a little circular, but it means
we don't have to create any new services which is good for a workshop.)
+
[source, java]
.GreetingServiceController.java
---------------------------------------------------------------------
    @GetMapping("/rest-call")
    Greeting restCall() {
        Greeting returnedGreeting = restTemplate.getForObject("/greeting", Greeting.class);
        return new Greeting("rest response: "+returnedGreeting.greeting);
    }
---------------------------------------------------------------------

. Build and launch the app

. Hit the endpoint at http://localhost:8080/rest-call

== Do it Reactive

Reactive Web is challenging to wrap your head around when you first encounter it.  You have to start thinking of the world in the basic Reactive types
of Mono and Flux.  There are a bunch of complicated operators to understand.  And the whole approach is functional (vs imperative) in nature.

MVC and WebFlux endpoints don't work in the same app, so we'll use a starter that already has some of the things we need (eg: Greeting class).  We'll add the greeting endpoints using a WebFlux style.  Then we'll look at the reactive based WebClient for making calls to other services.

. Open the starter in your IDE.
+
[source,bash]
---------------------------------------------------------------------
spring-workshop-2020:
├── labs
│   ├── web_and_reactive
│       └── greeting-service-reactive-starter
---------------------------------------------------------------------

Notice the project already contains the Greeting class, Configuration, and skeleton for the Service.

. There are different ways to declare end points in Web Flux.  We'll explore a mechanism that uses configuration to map a route to a call into a Service.
  The GreetingService class already as the Greeting bean wired in.  Now add a method to return it as a Mono.  This is the reactive way to create the
  service endpoint.
+
[source, java]
.GreetingReactiveService.java
---------------------------------------------------------------------
    public Mono<Greeting> getGreeting() {
        return Mono.just(new Greeting("hello, reactive"));
    }
---------------------------------------------------------------------

. Update GreetingServiceConfig by generating a bean that maps the route to the service method we just created
+
[source, java]
.GreetingServiceConfig.java
---------------------------------------------------------------------
    @Bean
    RouterFunction<?> routes(GreetingService greetingService) {
        return RouterFunctions
                .route(GET("/greeting"),
                        serverRequest -> ServerResponse.ok().body(greetingService.getGreeting(), Greeting.class));
    }
---------------------------------------------------------------------

. Run the app and see that the greeting endpoint works as expected.

== Reactive Web Client

We'll use the same trick with WebClient as we did with RestTemplate.

. This time, create the WebClient bean in the GreetingService using the available Builder class injected into the constructor.  Set the URL
to something appropriate for your environment.
+
[source, java]
.GreetingService.java
---------------------------------------------------------------------
    final private WebClient webClient;
    public GreetingService(WebClient.Builder builder, Greeting greeting) {
        super();
        this.greeting = greeting;
        this.webClient = builder.baseUrl("http://localhost:8080").build();
    }
---------------------------------------------------------------------

. Add the method to implement our service call
+
[source, java]
.GreetingService.java
---------------------------------------------------------------------
    public Mono<Greeting> webClientCall() {
        return webClient.get().uri("/greeting").retrieve().bodyToMono(Greeting.class);
    }
---------------------------------------------------------------------

. Update GreetingServiceConfig by adding a new route to the bean that maps the routes to service calls.
+
[source, java]
.GreetingServiceConfig.java
---------------------------------------------------------------------
    @Bean
    RouterFunction<?> routes(GreetingService greetingService) {
        return RouterFunctions
                .route(GET("/greeting"),
                        serverRequest -> ServerResponse.ok().body(greetingService.getGreeting(), Greeting.class))
                .andRoute(GET("/client-greeting"),
                        serverRequest -> ServerResponse.ok().body(greetingService.webClientCall(), Greeting.class));
    }
---------------------------------------------------------------------

. Run the application and see that the /client-greeting endpoint behaves as expected.

== Deploy to Pivotal Application Service
. Build the application and push it
+
[source,bash]
---------------------------------------------------------------------
$ mvn clean package
$ cf push
---------------------------------------------------------------------

. Verify the app works as expected.

*Congratulations!* This complets the introduction to Web MVC and WebFlux (Reactive Web)
